name: SLSA-Provenance
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  provenance:
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate provenance
        uses: slsa-framework/slsa-github-generator@v1.11.0
        with:
          artifact_path: .
          upload_assets: true
